# Map both Option keys to Alt/Meta.
macos_option_as_alt both

enable_audio_bell no

# Disable Kitty shortcuts so key presses are passed through to terminal apps.
clear_all_shortcuts yes
map cmd+plus change_font_size current +1.0
map cmd+minus change_font_size current -1.0
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+q quit

# Preserve Shift+Enter as a distinct key for tmux copy mode.
map shift+enter send_text all \x1b[13;2u

background #181818
hide_window_decorations no
macos_titlebar_color #181818
macos_show_window_title_in none
