#!/usr/bin/env python3

"""Select a path or extend an active selection using Unicode word boundaries."""

import sys

from copy_mode_word import run


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(2)
    run(sys.argv[1], "extend-path")
