-- Tags navigation: build-independent definition lookup with Swift scope hints.
-- Swift tags generated by gen_swift_tags.sh carry class/struct/extension scope fields;
-- Tree-sitter is used here only to infer the likely receiver type at the cursor.

local M = {}

local scope_keys = { "class", "struct", "enum", "actor", "protocol", "extension" }
local type_kinds = { a = true, c = true, e = true, p = true, s = true }

local function escape_tag_pattern(name)
    local escaped = {}
    local magic = {
        ["\\"] = true,
        ["."] = true,
        ["^"] = true,
        ["$"] = true,
        ["~"] = true,
        ["["] = true,
        ["]"] = true,
        ["*"] = true,
    }
    for index = 1, #name do
        local character = name:sub(index, index)
        escaped[#escaped + 1] = magic[character] and ("\\" .. character) or character
    end
    return "\\C^" .. table.concat(escaped) .. "$"
end

-- taglist() accepts a regular expression. Anchoring it is important: querying
-- "load" must not also return loadCached, loading, and every other prefix match.
local function exact_tags(name)
    local tags = vim.fn.taglist(escape_tag_pattern(name))
    for index, tag in ipairs(tags) do
        tag._tag_index = index
    end
    return tags
end

local function tag_scope(tag)
    for _, key in ipairs(scope_keys) do
        if tag[key] and tag[key] ~= "" then
            return tag[key], key
        end
    end
    return nil, nil
end

local function shorten(text, max)
    if #text <= max then
        return text
    end
    return "..." .. text:sub(#text - max + 4)
end

local function format_tag(tag)
    local scope = tag_scope(tag)
    local owner = scope and (scope .. ".") or ""
    local line = tag.line or tag.cmd or "?"
    local label = ("%-2s %s%s  %s:%s"):format(tag.kind or "?", owner, tag.name, tag.filename, line)
    return shorten(label, math.max(vim.o.columns - 4, 40))
end

local function jump_to_tag(name, tag)
    local winid = vim.api.nvim_get_current_win()
    local cursor = vim.api.nvim_win_get_cursor(winid)
    local from = { vim.api.nvim_get_current_buf(), cursor[1], cursor[2] + 1, 0 }

    local opened = pcall(vim.cmd.edit, vim.fn.fnameescape(tag.filename))
    if not opened then
        vim.notify(("Cannot open tag target: %s"):format(tag.filename), vim.log.levels.ERROR)
        return
    end

    local jumped = false
    local line = tonumber(tag.line or tag.cmd)
    if line then
        -- The generated line field disambiguates identical declarations in one file;
        -- a search pattern alone would always stop at the first `func load() {}`.
        vim.api.nvim_win_set_cursor(winid, { line, 0 })
        jumped = true
    elseif tag.cmd and tag.cmd:sub(1, 1) == "/" then
        vim.api.nvim_win_set_cursor(winid, { 1, 0 })
        jumped = pcall(vim.cmd, tag.cmd)
    end
    if not jumped then
        vim.notify(("Cannot locate tag target: %s"):format(name), vim.log.levels.ERROR)
        return
    end

    local stack = vim.fn.gettagstack(winid)
    stack.items = { { tagname = name, from = from } }
    vim.fn.settagstack(winid, stack, "t")
    vim.cmd("normal! zvzz")
end

local function choose_and_jump(name, tags, resolved_scope)
    local prompt = resolved_scope and ("Go to definition: %s [%s] (%d)"):format(name, resolved_scope, #tags)
        or ("Go to definition: %s (%d)"):format(name, #tags)
    vim.ui.select(tags, { prompt = prompt, format_item = format_tag }, function(tag)
        if tag then
            jump_to_tag(name, tag)
        end
    end)
end

local function direct_field_nodes(node, wanted_field)
    local result = {}
    for child, field in node:iter_children() do
        if field == wanted_field then
            result[#result + 1] = child
        end
    end
    return result
end

local function direct_field_node(node, field)
    return direct_field_nodes(node, field)[1]
end

local function node_text(node)
    return node and vim.treesitter.get_node_text(node, 0) or nil
end

local function direct_field_text(node, field)
    return node_text(direct_field_node(node, field))
end

local function normalize_type(type_name)
    if not type_name then
        return nil
    end
    type_name = vim.trim(type_name)
        :gsub("^:%s*", "")
        :gsub("^inout%s+", "")
        :gsub("^any%s+", "")
        :gsub("^some%s+", "")
        :gsub("[?!]+$", "")
    local nominal = type_name:match("^([%a_][%w_%.]*)")
    return nominal or nil
end

local function declaration_info(node)
    if node:type() == "class_declaration" then
        local kind = direct_field_text(node, "declaration_kind")
        local name = normalize_type(direct_field_text(node, "name"))
        return name, kind
    elseif node:type() == "protocol_declaration" then
        return direct_field_text(node, "name"), "protocol"
    end
    return nil, nil
end

local function first_inherited_type(node)
    for child in node:iter_children() do
        if child:type() == "inheritance_specifier" then
            for inherited in child:iter_children() do
                if inherited:named() then
                    local name = normalize_type(node_text(inherited))
                    if name then
                        return name
                    end
                end
            end
        end
    end
    return nil
end

local function enclosing_type(node)
    local names = {}
    local inherited = nil
    local current = node
    while current do
        local name, kind = declaration_info(current)
        if name then
            if kind == "extension" then
                table.insert(names, 1, name)
                return table.concat(names, "."), nil
            end
            if not inherited then
                inherited = first_inherited_type(current)
            end
            table.insert(names, 1, name)
        end
        current = current:parent()
    end
    return #names > 0 and table.concat(names, ".") or nil, inherited
end

local function pattern_contains_name(node, name)
    if node:type() == "simple_identifier" and node_text(node) == name then
        return true
    end
    for child in node:iter_children() do
        if child:named() and pattern_contains_name(child, name) then
            return true
        end
    end
    return false
end

local function inferred_initializer_type(value_node)
    if not value_node or value_node:type() ~= "call_expression" then
        return nil
    end
    for child in value_node:iter_children() do
        if child:named() then
            if child:type() == "simple_identifier" or child:type() == "navigation_expression" then
                return normalize_type(node_text(child))
            end
            return nil
        end
    end
    return nil
end

local function property_type(node, name)
    local owns_name = false
    for _, name_node in ipairs(direct_field_nodes(node, "name")) do
        if pattern_contains_name(name_node, name) then
            owns_name = true
            break
        end
    end
    if not owns_name then
        return nil, false
    end

    for child, field in node:iter_children() do
        if child:type() == "type_annotation" then
            return normalize_type(node_text(child)), true
        elseif field == "value" then
            local inferred = inferred_initializer_type(child)
            if inferred then
                return inferred, true
            end
        end
    end
    return nil, true
end

local function parameter_type(node, name)
    local fields = direct_field_nodes(node, "name")
    if #fields < 2 then
        return nil, false
    end
    for index = 1, #fields - 1 do
        if node_text(fields[index]) == name then
            return normalize_type(node_text(fields[#fields])), true
        end
    end
    return nil, false
end

local function starts_before(node, row, col)
    local start_row, start_col = node:start()
    return start_row < row or (start_row == row and start_col < col)
end

-- Resolve a simple receiver by walking lexical containers from the cursor outward.
-- This covers function parameters, preceding local bindings, and stored properties.
local function binding_type(cursor_node, name)
    local cursor_row, cursor_col = cursor_node:start()
    local current = cursor_node
    while current do
        local latest_type = nil
        local latest_row, latest_col = -1, -1
        local found_declaration = false
        for child in current:iter_children() do
            if child:named() then
                local candidate, declares_name = nil, false
                if child:type() == "parameter" then
                    candidate, declares_name = parameter_type(child, name)
                elseif
                    (child:type() == "property_declaration" or child:type() == "protocol_property_declaration")
                    and starts_before(child, cursor_row, cursor_col)
                then
                    candidate, declares_name = property_type(child, name)
                end
                if declares_name then
                    local row, col = child:start()
                    if row > latest_row or (row == latest_row and col > latest_col) then
                        latest_type, latest_row, latest_col = candidate, row, col
                        found_declaration = true
                    end
                end
            end
        end
        if found_declaration then
            return latest_type, true
        end
        current = current:parent()
    end
    return nil, false
end

local function receiver_node(symbol_node)
    local suffix = symbol_node and symbol_node:parent() or nil
    if not suffix or suffix:type() ~= "navigation_suffix" then
        return nil
    end
    local navigation = suffix:parent()
    if not navigation or navigation:type() ~= "navigation_expression" then
        return nil
    end
    return direct_field_node(navigation, "target")
end

local function is_known_type(name, tag_cache)
    if not name then
        return false
    end
    tag_cache[name] = tag_cache[name] or exact_tags(name)
    return vim.iter(tag_cache[name]):any(function(tag)
        return type_kinds[tag.kind] == true
    end)
end

local function inferred_scopes(symbol_node, tag_cache)
    local current_scope, inherited_scope = enclosing_type(symbol_node)
    local receiver = receiver_node(symbol_node)
    if not receiver then
        local scopes = {}
        if current_scope then
            scopes[#scopes + 1] = current_scope
        end
        if inherited_scope then
            scopes[#scopes + 1] = inherited_scope
        end
        return scopes
    end

    local receiver_text = node_text(receiver)
    if receiver:type() == "self_expression" or receiver_text == "self" then
        return current_scope and { current_scope, inherited_scope } or {}
    elseif receiver:type() == "super_expression" or receiver_text == "super" then
        return inherited_scope and { inherited_scope } or {}
    elseif receiver:type() ~= "simple_identifier" then
        return {}
    end

    local inferred, found_binding = binding_type(symbol_node, receiver_text)
    if found_binding then
        return inferred and { inferred } or {}
    end
    if is_known_type(receiver_text, tag_cache) then
        return { receiver_text }
    end
    return {}
end

local function matches_scope(tag, wanted_scope)
    local scope = tag_scope(tag)
    return scope == wanted_scope or (scope and scope:sub(-#wanted_scope - 1) == "." .. wanted_scope)
end

local function rank_by_location(tags)
    local current_file = vim.fs.normalize(vim.api.nvim_buf_get_name(0))
    local current_dir = vim.fs.dirname(current_file)
    table.sort(tags, function(left, right)
        local function score(tag)
            local filename = vim.fs.normalize(tag.filename)
            if filename == current_file then
                return 2
            elseif vim.fs.dirname(filename) == current_dir then
                return 1
            end
            return 0
        end
        local left_score, right_score = score(left), score(right)
        if left_score ~= right_score then
            return left_score > right_score
        end
        return left._tag_index < right._tag_index
    end)
end

local function scoped_candidates(name, tags)
    if vim.bo.filetype ~= "swift" then
        rank_by_location(tags)
        return tags, nil
    end

    local ok, parser = pcall(vim.treesitter.get_parser, 0, "swift")
    if not ok then
        rank_by_location(tags)
        return tags, nil
    end
    local parsed, trees = pcall(parser.parse, parser)
    if not parsed or not trees or not trees[1] then
        rank_by_location(tags)
        return tags, nil
    end

    local cursor = vim.api.nvim_win_get_cursor(0)
    local row, col = cursor[1] - 1, cursor[2]
    local symbol_node = trees[1]:root():descendant_for_range(row, col, row, col)
    if not symbol_node then
        rank_by_location(tags)
        return tags, nil
    end

    local tag_cache = { [name] = tags }
    for _, scope in ipairs(inferred_scopes(symbol_node, tag_cache)) do
        if scope then
            local matches = vim.tbl_filter(function(tag)
                return matches_scope(tag, scope)
            end, tags)
            if #matches > 0 then
                rank_by_location(matches)
                return matches, scope
            end
        end
    end

    rank_by_location(tags)
    return tags, nil
end

-- Go to definition using exact-name tags, then use Swift syntax and tag scope to
-- resolve common self/super/static/property/parameter/local-variable calls.
M.goto_def = function()
    local name = vim.fn.expand("<cword>")
    if name ~= "" then
        local tags = exact_tags(name)
        if tags[1] ~= nil then
            local candidates, resolved_scope = scoped_candidates(name, tags)
            if #candidates == 1 then
                jump_to_tag(name, candidates[1])
            else
                choose_and_jump(name, candidates, resolved_scope)
            end
            return
        end
    end
    vim.cmd("normal! gd")
end

-- Go to a declaration-kind tag where the language provides one; Swift uses the
-- same scope-aware definition path because its tags do not distinguish declarations.
M.goto_decl = function()
    if vim.bo.filetype == "swift" then
        M.goto_def()
        return
    end
    local name = vim.fn.expand("<cword>")
    if name ~= "" then
        local declarations = vim.tbl_filter(function(tag)
            return tag.kind == "p" or tag.kind == "d"
        end, exact_tags(name))
        if #declarations == 1 then
            jump_to_tag(name, declarations[1])
            return
        elseif #declarations > 1 then
            choose_and_jump(name, declarations)
            return
        end
    end
    vim.cmd("normal! gD")
end

-- Find references with ripgrep; tags contain definitions, not references.
M.find_refs = function()
    local name = vim.fn.expand("<cword>")
    if name == "" then
        return
    end
    if vim.fn.executable("rg") ~= 1 then
        vim.notify("Finding references requires ripgrep (rg)", vim.log.levels.WARN)
        return
    end
    local cmd = {
        "rg",
        "--vimgrep",
        "-w",
        "--no-heading",
        "--color=never",
        "-g",
        "!tags",
        "-g",
        "!.git",
        name,
        vim.fn.getcwd(),
    }
    local out = vim.system(cmd, { text = true }):wait()
    if out.code ~= 0 or not out.stdout or out.stdout == "" then
        vim.notify(("No references found for '%s'"):format(name), vim.log.levels.INFO)
        return
    end
    local qf = {}
    for line in vim.gsplit(out.stdout, "\n", { trimempty = true }) do
        local file, lnum, col, text = line:match("^(.-):(%d+):(%d+):(.*)$")
        if file then
            qf[#qf + 1] = { filename = file, lnum = tonumber(lnum), col = tonumber(col), text = text }
        end
    end
    if #qf > 0 then
        vim.fn.setqflist(qf)
        vim.cmd("copen")
        vim.notify(("%d reference(s)"):format(#qf), vim.log.levels.INFO)
    end
end

M.list_tags = function()
    local name = vim.fn.expand("<cword>")
    if name == "" then
        return
    end
    local tags = exact_tags(name)
    if tags[1] == nil then
        vim.notify(("'%s' not found in tags"):format(name), vim.log.levels.INFO)
        return
    end
    choose_and_jump(name, tags)
end

return M
